-- CreateEnum
CREATE TYPE "HISTORICAL_RANGE_STATUS" AS ENUM ('PENDING', 'FINALIZED');

-- AlterTable
ALTER TABLE "historical_sync_range" ADD COLUMN     "status" "HISTORICAL_RANGE_STATUS" NOT NULL DEFAULT 'PENDING';
